### ISSUE TITLE
Trail bugs out

### ISSUE THREAD

**Issue by Abstath** [portify/Server_NewBrickTool#1]
Holding left-click while switching to another item causes the trail to bug out.

**Comment by qoh** [comment]
Are you sure that you're using the latest version? This shouldn't be an issue in v1.1.0. See https://github.com/portify/Server_NewBrickTool/blob/25b8386719d4ecac15c7f5e126a2f513b80967ad/server.cs#L372-L381

**Comment by Abstath** [comment]
This issue only existed in the first version; forgot to close this.
